import { createClient } from '@supabase/supabase-js';

// Configuración de Supabase
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-anon-key';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Tipos para las tablas de Supabase
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          phone?: string;
          avatar?: string;
          user_type: 'visitor' | 'registered' | 'verified' | 'premium' | 'admin';
          verified_at?: string;
          created_at: string;
          updated_at: string;
          preferences?: any;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          phone?: string;
          avatar?: string;
          user_type?: 'visitor' | 'registered' | 'verified' | 'premium' | 'admin';
          verified_at?: string;
          created_at?: string;
          updated_at?: string;
          preferences?: any;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          phone?: string;
          avatar?: string;
          user_type?: 'visitor' | 'registered' | 'verified' | 'premium' | 'admin';
          verified_at?: string;
          created_at?: string;
          updated_at?: string;
          preferences?: any;
        };
      };
      properties: {
        Row: {
          id: string;
          title: string;
          description: string;
          address: string;
          neighborhood: string;
          city: string;
          coordinates: any;
          bedrooms: number;
          bathrooms: number;
          area: number;
          parking: number;
          floor?: number;
          total_floors?: number;
          year_built?: number;
          property_type: 'apartment' | 'house' | 'townhouse' | 'office' | 'commercial';
          strata?: number;
          price: number;
          monthly_costs?: number;
          accepts_crypto: boolean;
          financing: boolean;
          visit_price: number;
          status: 'draft' | 'pending' | 'published' | 'sold' | 'rented' | 'archived';
          verified: boolean;
          premium: boolean;
          images: string[];
          virtual_tour?: string;
          freedom_tradition?: string;
          legal_documents?: string[];
          owner_id: string;
          agent_id?: string;
          tags: string[];
          features: string[];
          created_at: string;
          updated_at: string;
          published_at?: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          address: string;
          neighborhood: string;
          city: string;
          coordinates: any;
          bedrooms: number;
          bathrooms: number;
          area: number;
          parking: number;
          floor?: number;
          total_floors?: number;
          year_built?: number;
          property_type: 'apartment' | 'house' | 'townhouse' | 'office' | 'commercial';
          strata?: number;
          price: number;
          monthly_costs?: number;
          accepts_crypto?: boolean;
          financing?: boolean;
          visit_price: number;
          status?: 'draft' | 'pending' | 'published' | 'sold' | 'rented' | 'archived';
          verified?: boolean;
          premium?: boolean;
          images: string[];
          virtual_tour?: string;
          freedom_tradition?: string;
          legal_documents?: string[];
          owner_id: string;
          agent_id?: string;
          tags: string[];
          features: string[];
          created_at?: string;
          updated_at?: string;
          published_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          address?: string;
          neighborhood?: string;
          city?: string;
          coordinates?: any;
          bedrooms?: number;
          bathrooms?: number;
          area?: number;
          parking?: number;
          floor?: number;
          total_floors?: number;
          year_built?: number;
          property_type?: 'apartment' | 'house' | 'townhouse' | 'office' | 'commercial';
          strata?: number;
          price?: number;
          monthly_costs?: number;
          accepts_crypto?: boolean;
          financing?: boolean;
          visit_price?: number;
          status?: 'draft' | 'pending' | 'published' | 'sold' | 'rented' | 'archived';
          verified?: boolean;
          premium?: boolean;
          images?: string[];
          virtual_tour?: string;
          freedom_tradition?: string;
          legal_documents?: string[];
          owner_id?: string;
          agent_id?: string;
          tags?: string[];
          features?: string[];
          created_at?: string;
          updated_at?: string;
          published_at?: string;
        };
      };
      visits: {
        Row: {
          id: string;
          property_id: string;
          visitor_id: string;
          scheduled_date: string;
          scheduled_time: string;
          status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'rescheduled';
          visit_price: number;
          paid: boolean;
          payment_method?: 'cash' | 'card' | 'crypto';
          nda_accepted: boolean;
          feedback?: string;
          rating?: number;
          notes?: string;
          documents_unlocked: boolean;
          created_at: string;
          updated_at: string;
          completed_at?: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          visitor_id: string;
          scheduled_date: string;
          scheduled_time: string;
          status?: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'rescheduled';
          visit_price: number;
          paid?: boolean;
          payment_method?: 'cash' | 'card' | 'crypto';
          nda_accepted?: boolean;
          feedback?: string;
          rating?: number;
          notes?: string;
          documents_unlocked?: boolean;
          created_at?: string;
          updated_at?: string;
          completed_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          visitor_id?: string;
          scheduled_date?: string;
          scheduled_time?: string;
          status?: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'rescheduled';
          visit_price?: number;
          paid?: boolean;
          payment_method?: 'cash' | 'card' | 'crypto';
          nda_accepted?: boolean;
          feedback?: string;
          rating?: number;
          notes?: string;
          documents_unlocked?: boolean;
          created_at?: string;
          updated_at?: string;
          completed_at?: string;
        };
      };
      offers: {
        Row: {
          id: string;
          property_id: string;
          buyer_id: string;
          offer_price: number;
          original_price: number;
          payment_method: 'cash' | 'financing' | 'crypto' | 'mixed';
          financing_details?: any;
          crypto_details?: any;
          closing_date: string;
          conditions: string[];
          status: 'pending' | 'accepted' | 'rejected' | 'countered' | 'expired';
          counter_offer?: any;
          metrics: any;
          created_at: string;
          expires_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          buyer_id: string;
          offer_price: number;
          original_price: number;
          payment_method: 'cash' | 'financing' | 'crypto' | 'mixed';
          financing_details?: any;
          crypto_details?: any;
          closing_date: string;
          conditions: string[];
          status?: 'pending' | 'accepted' | 'rejected' | 'countered' | 'expired';
          counter_offer?: any;
          metrics: any;
          created_at?: string;
          expires_at: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          buyer_id?: string;
          offer_price?: number;
          original_price?: number;
          payment_method?: 'cash' | 'financing' | 'crypto' | 'mixed';
          financing_details?: any;
          crypto_details?: any;
          closing_date?: string;
          conditions?: string[];
          status?: 'pending' | 'accepted' | 'rejected' | 'countered' | 'expired';
          counter_offer?: any;
          metrics?: any;
          created_at?: string;
          expires_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'visit_scheduled' | 'offer_received' | 'offer_accepted' | 'contract_ready' | 'payment_received';
          title: string;
          message: string;
          read: boolean;
          related_id?: string;
          related_type?: 'property' | 'offer' | 'visit' | 'contract';
          created_at: string;
          read_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'visit_scheduled' | 'offer_received' | 'offer_accepted' | 'contract_ready' | 'payment_received';
          title: string;
          message: string;
          read?: boolean;
          related_id?: string;
          related_type?: 'property' | 'offer' | 'visit' | 'contract';
          created_at?: string;
          read_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'visit_scheduled' | 'offer_received' | 'offer_accepted' | 'contract_ready' | 'payment_received';
          title?: string;
          message?: string;
          read?: boolean;
          related_id?: string;
          related_type?: 'property' | 'offer' | 'visit' | 'contract';
          created_at?: string;
          read_at?: string;
        };
      };
    };
  };
}

