project_id = "sunday_proto"

[api]
enabled = true
port = 54327
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54326
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seeds/seed-local.sql"]

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54327"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54329